name: Java CI/CD with Kubernetes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [book-service, member-service, loan-service]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -f ${{ matrix.service }}/pom.xml clean package -DskipTests

    - name: Build Docker image
      run: |
        docker build -t ${{ matrix.service }}:latest ./${{ matrix.service }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
    - name: Deploy to K8s
      run: |
        kubectl apply -f k8s-manifests.yaml
